library utils_tests;

import 'dart:async';
import 'dart:io';

import 'markdown_configuration.dart';
import 'package:unittest/unittest.dart';

import '../lib/neo4dart.dart';

Future<Neo4Dart> initialize() {
  List path = Platform.script.pathSegments.getRange(0, Platform.script.pathSegments.length-2).fold(new List(), (List list, String segment) => list..add(segment))..add('doc/result.md');
  unittestConfiguration = new MakedownConfiguration(Platform.pathSeparator + path.join(Platform.pathSeparator),
      ['#REST Api compatibility check list  \n',
       '  \n',
       '  \n',
       'This check list is based on the [REST api documentation](http://docs.neo4j.org/chunked/snapshot/rest-api.html) of Neo4j 2.0 snapshot  \n',
       'This file is generated by automated unit-tests  \n',
       '  \n',
       '  \n',
       '  \n',
       '##Results  \n',
       '  \n'
       ]);
  
  return Neo4Dart.init("127.0.0.1");
}

const String NOT_YET_IMPLEMENTED = '(not yet implemented)';
void notYetImplemented() {
  fail(NOT_YET_IMPLEMENTED);
}
